In [ ]:
import numpy as np

In [ ]:
##creating 1D array using numpy
arr1=np.array([1,2,3,4,6,7,7,8,])
print(arr1)


[1 2 3 4 6 7 7 8]


In [ ]:
print(arr1.shape)

(8,)


In [ ]:
##reshape array into 2D
arr2=np.array([1,2,3,4,5,6,7])
arr2.reshape(1,7) #1 row and 5 columns



array([[1, 2, 3, 4, 5, 6, 7]])

In [ ]:
np.arange(0,10,2) # start from 0 , end at 10, steps 2

array([0, 2, 4, 6, 8])

In [ ]:
np.ones((3,4)) # 3 rows and 4 col and it gives all one in matrix


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#number of dimentions
arr2.ndim

1

In [ ]:
#size of matrix i.e number of elements
arr2.size

7

In [ ]:
#Data types
arr2.dtype

dtype('int64')

In [ ]:
#item size
arr2.itemsize

8

In [ ]:
##numpy vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## element wise addition
print("Addition:", arr1+arr2)

##element wise subtraction
print("subtraction:", arr2-arr1)

##element wise multiplication
print("Multiplication:", arr2*arr1)

##element wise Division
print("Division:", arr2//arr1)


Addition: [11 22 33 44 55]
subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10 10 10 10 10]


In [ ]:
##Universal Function
#sqaure root
print(np.sqrt(arr2))

# Exponential
print(np.exp(arr1))

# sine
print(np.sin(arr1))

#natural log
print(np.log(arr1))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
## Array slicing and Indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n", arr)


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[1][0:])

[5 6 7 8]


In [ ]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
arr[0:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
print(arr[1,1:3])
print(arr[1:,1:3])

[6 7]
[[ 6  7]
 [10 11]]


In [ ]:
##modify array elements
arr[0,0]=100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [ ]:
arr[1:]=100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [ ]:
arr[2:]=[100,200,300,400]
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 200, 300, 400]])

In [ ]:
## Statistical Concept -  Normalization
#To have a mean of 0 and Standard Deviation of 1
Data=np.array([10,20,30,40,50])

#Calculating Mean and Standard deviation\
mean = np.mean(Data)
print("Mean:\n",mean)

median = np.median(Data)
print("Median:\n", median)


std_dev=np.std(Data)
print("Standard Deviation:\n", std_dev)

var = np.var(Data)
print("Variance:\n", var)

#Normalize the Data
normalized_data = (Data-mean)/std_dev
print(normalized_data)

Mean:
 30.0
Median:
 30.0
Standard Deviation:
 14.142135623730951
Variance:
 200.0
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
#Logical Operations

Data = np.array([1,2,3,4,5,6,7,8,9,10])
print(Data>5)  # give True Flase Value
print(Data[Data>5]) # with the help of indexing it gives array values directly

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


In [ ]:
Data[(Data>5) & (Data<=8)]

array([6, 7, 8])